// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYnFlFA02dVu27yJX_ivXoTXhr8J5rLF8',
    appId: '1:417279491236:web:58fa8c25c97c12a09f3a31',
    messagingSenderId: '417279491236',
    projectId: 'prueba-de-flutter-47ab5',
    authDomain: 'prueba-de-flutter-47ab5.firebaseapp.com',
    storageBucket: 'prueba-de-flutter-47ab5.firebasestorage.app',
    measurementId: 'G-CTS09R1B93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFtJqrbiN_-Rn8O6MAl4AP-9V1ZgDIVs',
    appId: '1:417279491236:android:ca3e9b281d088c699f3a31',
    messagingSenderId: '417279491236',
    projectId: 'prueba-de-flutter-47ab5',
    storageBucket: 'prueba-de-flutter-47ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLtIAjQTrVhygSUIOHY2mFSWZaM7iyoM',
    appId: '1:417279491236:ios:02ba1ed6341ade3a9f3a31',
    messagingSenderId: '417279491236',
    projectId: 'prueba-de-flutter-47ab5',
    storageBucket: 'prueba-de-flutter-47ab5.firebasestorage.app',
    iosBundleId: 'com.example.pruebaFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLtIAjQTrVhygSUIOHY2mFSWZaM7iyoM',
    appId: '1:417279491236:ios:02ba1ed6341ade3a9f3a31',
    messagingSenderId: '417279491236',
    projectId: 'prueba-de-flutter-47ab5',
    storageBucket: 'prueba-de-flutter-47ab5.firebasestorage.app',
    iosBundleId: 'com.example.pruebaFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYnFlFA02dVu27yJX_ivXoTXhr8J5rLF8',
    appId: '1:417279491236:web:164997d8f972824e9f3a31',
    messagingSenderId: '417279491236',
    projectId: 'prueba-de-flutter-47ab5',
    authDomain: 'prueba-de-flutter-47ab5.firebaseapp.com',
    storageBucket: 'prueba-de-flutter-47ab5.firebasestorage.app',
    measurementId: 'G-G6FGKYQ9K1',
  );
}
